music/urls.py
from django.urls import path
from . import views

app_name = 'music'

urlpatterns = [
	#music/
	path('', views.IndexView.as_view(), name='index'),

	#music/{album_id}/
	path('<pk>/', views.DetailsView.as_view(), name='details'),

	#music/add
	path('album/add', views.AlbumCreate.as_view(), name = 'album-add'),

	#music/album/{album_id}/
	path('album/<pk>/', views.AlbumUpdate.as_view(), name = 'album-update'),

	#music/<pk>/delete
	path('album/<pk>/delete', views.AlbumDelete.as_view(), name = 'album-delete')	

	#music/{album_id}/favourite/
	#path('<album_id>/favourite', views.favourite, name='favourite'),	---->>NOT USING FAVOURITE FEATURE NOW
]

website/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
   	path('music/', include('music.urls')),
]

music/models.py
from django.db import models
from django.urls import reverse 

class Album (models.Model):
	artist = models.CharField(max_length=250)
	album_title = models.CharField(max_length=100)
	genre = models.CharField(max_length=100)
	album_logo = models.CharField(max_length=100)

	def get_absolute_url(self):
		return reverse('music:details',kwargs={'pk':self.pk})


	def __str__(self):
		return self.album_title + " - " + self.artist

class Song(models.Model):
	album = models.ForeignKey(Album, on_delete=models.CASCADE)
	file_type = models.CharField(max_length=10)
	song_title = models.CharField(max_length=250)
	isFavourite = models.BooleanField(default=False)

	def __str__(self):
		return self.song_title 

music/views.py
#from django.http import Http404
#from django.shortcuts import render,get_object_or_404
from django.views import generic
from .models import Album
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy

class IndexView (generic.ListView):
	context_object_name = 'all_albums'
	template_name = 'music/index.html'

	def get_queryset(self):
		return Album.objects.all()


class DetailsView (generic.DetailView):
	model = Album
	template_name = 'music/detail.html'	

class AlbumCreate(CreateView):
	model = Album
	fields = ['artist','album_title','genre','album_logo']

class AlbumUpdate(UpdateView):
	model = Album
	fields = ['artist','album_title','genre','album_logo']
	
class AlbumDelete(DeleteView):
	model = Album
	success_url = reverse_lazy('music:index')
						
					

'''
def index(request):
	all_albums = Album.objects.all()
	context = {'all_albums' : all_albums}
	return render(request,'music/index.html',context)

def details(request, album_id):
	album = get_object_or_404(Album, pk = album_id)
	return render(request, 'music/detail.html', {'album' : album})

def favourite(request,album_id):
	album = get_object_or_404(Album, pk = album_id)
	try:
		selected_song = album.song_set.get(pk = request.POST['song'])
	except (KeyError, Song.DoesNotExist):
		return render(request,'music/detail.html',{'album' : album, 'error_msg' : "You did not select a valid song",})
	else:
		selected_song.isFavourite = True
		selected_song.save()
		return render(request, 'music/detail.html', {'album' : album})		'''

music/templates/music/album_form.html
{% extends 'music/base.html' %}

{% block title %} Album Details {% endblock %}

{% block body %}
<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {% include 'music/form_template.html' %}



</form>
  
{% endblock%}

music/templates/music/base.html
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet">
  <title>{% block title %} MyMusic {% endblock %}</title>
</head>
<body>

<!-- Loads path to the static files-->

{% load staticfiles%}
<link rel="stylesheet" type="text/css" href="{% static 'music/style.css'%}"/>



<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd">
  <a class="navbar-brand" style="font-family: Indie Flower; " href="#"><strong>MyMusic</strong></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item">
        <a class="nav-link" href="{% url 'music:index'%}">Albums</a>
      </li>
      
      <li class="nav-item">
        <a class="nav-link" href="{%url 'music:album-add'%}"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>Add Album</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="#"><span class="glyphicon glyphicon-off" aria-hidden="true"></span>Logout</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

  {%block body%}
  {% endblock %}
</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}

{% block title %} Album Details {% endblock %}



{% block body %}

<div class="col-sm-4" style="float: left;width: 23rem;background-color: #fff;">
	<div class="card">
	<img class="card-img-top" src = "{{album.album_logo}}"/>
	</div>
	<div class="card-body">		
		<h1>{{album.album_title}}</h1>

		<h2>{{album.artist}}</h2>

		<h3>{{album.genre}}</h3><br>
		 <form action="{% url 'music:album-update' album.id %} " method="post">
				    	{% csrf_token %}
					    <button type="submit" class="btn btn-outline-success">Update</button>	
				    </form>
		{% if error_msg%}
		<p><strong> {{error_msg}}</strong></p>
	{% endif %}
	<br>
	<ul class="list-group list-group-flush">
		{% csrf_token %}
		{% for song in album.song_set.all %}

				<li class="list-group-item">{{song.song_title}}</li>
				
		{% endfor%}

	</ul>

	</div>
</div>

<div class="card col-sm-8" style="padding-left: 30vw;">

	<h3> Add song to the album</h3>
	</div>



{% endblock %}

music/templates/music/form_template.html
<div class="col-sm-4">
	<div class="card">
		{%for field in form%}
				<div class="form-group">
					<div class="col-sm-offset-2 col-sm-10">
						<span class="text-danger small">{{field.errors}}</span>
					</div>
					<label class="control-label col-sm-2">{{field.label_tag}}</label>
					<div class="col-sm-10">{{field}}</div>
				</div>
		{%endfor%}
		  <button type="submit" class="btn btn-success">Submit</button>
	</div>
</div>

music/templates/music/index.html
{% extends 'music/base.html' %}

{% block body %}
<h2> Here is the list of all my albums</h2>

{% if all_albums %}

	<div class="row">
	{% for album in all_albums %}
		<div class="col-sm-4">

				<div class="card" style="width: 23rem;">

				  <img class="card-img-top" src="{{album.album_logo}}" alt="Card image cap">

				  <div class="card-body">

				    <h5 class="card-title">{{album.album_title}}</h5>

				    <p class="card-text">{{album.artist}}</p>

				    <a style="float: left;margin-right: 2px;" href="{% url 'music:details' album.id%}" class="btn btn-outline-info" role="button">View Songs</a>
				    
				    <form action="{% url 'music:album-delete' album.id %} " method="post">
				    		{% csrf_token %}
				    	<button type="submit" class="btn btn-outline-danger">Delete</button>	
				    </form>
				    
				  </div>

				</div>
		</div>
	{% endfor %}
	</div>

{%else %} 
	<h3>You don't have any music albums</h3>

{% endif %}

{% endblock %}